openapi: 3.1.0
info:
  title: API для проекта "Шесть городов"
  description: |-
    * Список ресурсов и маршрутов сервера «Куплю. Продам».
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
tags:
  - name: offers
    description:  Действия с объявлениями.
  - name: comments
    description: Действия с комментариями.
  - name: users
    description: Действия с пользователем.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя

      requestBody:
        description: Информация для создания нового пользовтеля
        content:
          application/json:
            $ref: '#/components/schemas/createUser'
        requered: true
    
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь с таким email уже существует
          
  /uers/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизирует пользователя на основе логина и пароля
    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизированному пользователю

components:
  schemas:
    createUser:
      type: object

      properties:
        name:
          type: string
          example: Stanislav

        email:
          type: string
          example: svitkov@gmail.com

        avatarPath:
          type: string
          example: /images/avatar.png

        password:
          type: string
          example: 123321
    
    user:
      type: object

      properties:
        id:
          type: string
          example: 6329c3d6a04ab1061c6425ea

        email:
          type: string
          example: test@gmail.com